trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: pogosoftware/ansible-lint:0.2.2

steps:
- script: ansible-lint ./**/*.yml
  displayName: Run Ansible Lint

- script:  yamllint -c /etc/ansible/yamllint.yaml ./**/*.yml
  displayName: Run Yaml Lint
