name: Ansible Role LVM lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Run ansible-lint
      uses: docker://cytopia/ansible-lint
      with:
        args: .

    - name: Run yamllint
      uses: docker://cytopia/yamllint
      with:
        args: .
